program: src/eval_diffusion.py

method: grid

metric: # Does not matter, as we are using sweep to run the experiment.
  goal: minimize
  name: test/loss

parameters:
  data:
    value: qm9_only

  diffusion_module:
    value: ldm

  seed:
    values: 
    - 9
    - 99

  ckpt_path:
    value: "/home/ckj24/adit-geom/logs/train_diffusion/runs/DiT-B__vae_latent@8_kl@0.00001_GEOM_resume1405_2025-05-14_07-47-54/checkpoints/last.ckpt"

  ++diffusion_module.autoencoder_ckpt:
    value: "/home/ckj24/adit-geom/logs/train_autoencoder/runs/vae_latent@8_kl@0.00001_GEOM_2025-05-11_23-17-48/checkpoints/vae-epoch@24-step@14300-val_geom_match_rate@0.9903.ckpt"

  ++diffusion_module.denoiser.d_model:
    value: 768  # 384, 768, 1024
  ++diffusion_module.denoiser.nhead:
    value: 12  # 6, 12, 16
  ++diffusion_module.denoiser.num_layers:
    value: 12  # 12, 12, 24

  ++diffusion_module.interpolant.num_timesteps:
    values: [
      250,
      500,
      1000,
    ]

  ++diffusion_module.sampling.cfg_scale:
    values: [
      2.0,
      4.0,
    ]

  ++diffusion_module.sampling.removeHs:
    value: true

  ++diffusion_module.sampling.num_samples:
    value: 10000

  ++diffusion_module.sampling.batch_size:
    value: 500

  trainer:
    value: gpu

  logger:
    value: wandb

  name:
    value: "ADiT-B_eval_nt@${diffusion_module.interpolant.num_timesteps}_cfg@${diffusion_module.sampling.cfg_scale}"

command:
  - ${env}
  - HYDRA_FULL_ERROR=1
  - WANDB_START_METHOD=thread
  - python
  - ${program}
  - ${args_no_hyphens}
