program: src/eval_diffusion.py

method: grid

metric: # Does not matter, as we are using sweep to run the experiment.
  goal: minimize
  name: test/loss

parameters:
  data:
    value: joint

  diffusion_module:
    value: ldm

  seed:
    value: 9

  ckpt_path:
    value: "/home/ckj24/adit-geom/logs/geom_ckpt/ldm-epoch@299-step@185194-val_qm9_valid_rate@0.9600.ckpt"

  ++diffusion_module.autoencoder_ckpt:
    value: "/home/ckj24/adit-geom/logs/geom_ckpt/vae-epoch@74-step@85275-val_qm9_match_rate@0.9922.ckpt"

  ++diffusion_module.interpolant.num_timesteps:
    values: [
      500,
      1000,
    ]

  ++diffusion_module.sampling.cfg_scale:
    values: [
      2.0,
      4.0,
    ]

  ++diffusion_module.sampling.removeHs:
    values: [
      true,
      false,
    ]

  ++diffusion_module.sampling.num_samples:
    value: 10000

  ++diffusion_module.sampling.batch_size:
    value: 2000

  trainer:
    value: gpu

  logger:
    value: wandb

  name:
    value: "GEOM_eval_nt@${diffusion_module.interpolant.num_timesteps}_cfg@${diffusion_module.sampling.cfg_scale}"

command:
  - ${env}
  - HYDRA_FULL_ERROR=1
  - WANDB_START_METHOD=thread
  - python
  - ${program}
  - ${args_no_hyphens}
